# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='enc',
        ),
    ]
