# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_myuser_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='encrypted_data',
            field=models.CharField(default='sometext', max_length=30),
            preserve_default=False,
        ),
    ]
