# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180626_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
