# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myuser_encrypted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='pic_folder/no-img.jpg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='encrypted_data',
            field=models.CharField(max_length=300),
        ),
    ]
