# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180710_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='picture_id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='avatars/'),
        ),
    ]
