# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_registrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.CharField(max_length=30)),
                ('user_token', models.TextField(max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
