# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180626_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
