# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_changepasswordrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together=set([('email', 'username')]),
        ),
    ]
