# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180626_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='location',
        ),
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='myuser',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
