# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180626_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
