# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180801_1845'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together=set([('email',)]),
        ),
    ]
