# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180705_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(default='Mordor', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default=5605842, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='postal_code',
            field=models.CharField(default=4465925, max_length=30),
            preserve_default=False,
        ),
    ]
