# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180705_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
