# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_myuser_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='image',
            new_name='picture_id',
        ),
    ]
